fix: fix deps
swc-project/swc-loader pull request #23
Opened 2021-09-12 07:42 UTC by codeudan

1.move @swc/core in dependencies  to devDependencies. if  "@swc/core" in "dependencies", it will be installed twice when user  install it  , it should in devDependencies
2.@swc/core in peerDependencies should a loose version

2021-09-12 07:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc-loader?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc-loader?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc-loader?pullRequest=23) it.</sub>

2021-09-14 06:45 UTC, codeudan commented
@kdy1  hi~, can you help to review this pr?😀

2021-09-14 06:47 UTC, kdy1 requested changes

2021-09-14 06:47 UTC, kdy1 commented on package.json
> +        "@swc/core": "^1.2.0",
Please use `^1.2.52`.
`@swc/cli` pass a hidden argument to `@swc/core`.

2021-09-14 07:07 UTC, codeudan commented on package.json
> +        "@swc/core": "^1.2.0",
@kdy1 Done.

2021-09-14 07:08 UTC, kdy1 approved these changes
Thanks!

2021-09-14 07:08 UTC, merged